image:
  # -- image repository
  repository: linuxserver/faster-whisper
  # -- image tag
  tag: "2.4.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [linkwarden documentation](https://github.com/linkwardenco/linkwarden).
# @default -- See below
env: 
    PGID: '1000'
    PUID: '1000'
    TZ: Etc/UTC
    WHISPER_BEAM: '1'
    WHISPER_LANG: 'fr'
    WHISPER_MODEL: 'tiny-int8'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 10300

ingress:
  main:
    enabled: true
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-dns
    ingressClassName: "traefik"
    hosts: 
       - host: faster-whisper.p.zacharie.org
         paths:
           - path: /
             pathType: Prefix
    tls:
      - secretName: faster-whisper.p.zacharie.org-tls
        hosts:
          - faster-whisper.p.zacharie.org

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    mountPath: /config
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: "longhorn"
    matchLabels: {}
    matchExpressions: {}

