apiVersion: v2
appVersion: "1.7.0"
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: whisperx helm package
kubeVersion: ">=1.16.0-0"
name: whisperx
version: 0.1.2
