apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-web-service
spec:
  type: {{ .Values.web.service.type }}
  ports:
  - port: {{ .Values.web.service.port }}
    targetPort: {{ .Values.web.service.port }}
    nodePort: {{ .Values.web.service.nodePort }}
  selector:
    app: {{ .Values.global.appName }}-web
