{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "antigravity.fullname" . }}-secrets
  labels:
    {{- include "antigravity.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    {{- toYaml .Values.externalSecret.secretStoreRef | nindent 4 }}
  target:
    name: {{ include "antigravity.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    {{- range $key, $val := .Values.externalSecret.remoteRefs }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $val.key }}
        property: {{ $val.property }}
    {{- end }}
{{- end }}
