apiVersion: v2
name: kryptos
description: Cyber Premium Secrets Manager & GitOps Hub
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - kryptos
  - security
  - secrets
  - gitops
maintainers:
  - name: Joseph
