image:
  # -- image repository
  repository: tabbyml/tabby
  # -- image tag
  tag: "0.24.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      http:
        port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: true
    mountPath: /data
