replicaCount: 1

image:
  repository: ghcr.io/jzacharie/mnemosyne-ui
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: regcred

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: search.p.zacharie.org
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: mnemosyne-ui-tls
      hosts:
        - search.p.zacharie.org

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}
tolerations: []
affinity: {}

config:
  mnemosyneUrl: "http://mnemosyne.mnemosyne.svc.cluster.local:8080"
  ollamaUrl: "http://ollama.ollama.svc.cluster.local:11434"
  ollamaModel: "llama3"
