apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-nfs-pv
spec:
  capacity:
    storage: {{ .Values.nfs.capacity }}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
  storageClassName: nfs-static
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 10Gi
  volumeName: {{ .Release.Name }}-nfs-pv
