image:
  # -- image repository
  repository: aceberg/watchyourlan
  # -- image tag
  tag: "2.0.4"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [linkwarden documentation](https://github.com/linkwardenco/linkwarden).
# @default -- See below
# env: 
#     NEXTAUTH_URL: http://localhost:3000/api/v1/auth
#     NEXTAUTH_SECRET: 
#     DATABASE_URL: 

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8840

ingress:
  main:
    enabled: true
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-dns
    ingressClassName: "traefik"
    hosts: 
       - host: watchyourlan.p.zacharie.org
         paths:
           - path: /
             pathType: Prefix
    tls:
      - secretName: watchyourlan.p.zacharie.org-tls
        hosts:
          - watchyourlan.p.zacharie.org


# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  data:
    enabled: false
    mountPath: /data
