image:
  # -- image repository
  repository: seemeai/crewai
  # -- image tag
  tag: "crewai-0.102.0-tools-0.36.0-chainlit-2.2.0"
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- environment variables. See more environment variables in the [linkwarden documentation](https://github.com/linkwardenco/linkwarden).
# @default -- See below
# env: 
#     NEXTAUTH_URL: http://localhost:3000/api/v1/auth
#     NEXTAUTH_SECRET: 
#     DATABASE_URL: 

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 8888
  other:
    ports:
      http:
        port: 6006        

ingress:
  main:
    enabled: true
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-dns
    ingressClassName: "traefik"
    hosts: 
       - host: crewai.p.zacharie.org
         paths:
           - path: /
             pathType: Prefix
    tls:
      - secretName: crewai.p.zacharie.org-tls
        hosts:
          - crewai.p.zacharie.org

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
# persistence:
#   hf-hub-cache:
#     enabled: true
#     mountPath: /home/ubuntu/.cache/huggingface/hub
#     accessMode: ReadWriteOnce
#     size: 1Gi
#     storageClass: "longhorn"
#     matchLabels: {}
#     matchExpressions: {}