apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencode.fullname" . }}-config
  labels:
    {{- include "opencode.labels" . | nindent 4 }}
data:
  opencode.json: |
    {{ .Values.opencodeConfig | toJson | nindent 4 }}
