apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inova-monitoring.fullname" . }}-env
  labels:
    {{- include "inova-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_HOST: {{ .Values.postgresql.host | quote }}
  POSTGRES_PORT: {{ .Values.postgresql.port | quote }}
  POSTGRES_USER: {{ .Values.postgresql.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | quote }}
  POSTGRES_DB: {{ .Values.postgresql.db | quote }}
  PROMETHEUS_URL: {{ .Values.prometheus.url | quote }}
  DEBUG: {{ .Values.app.debug | quote }}
  API_SECRET_KEY: {{ .Values.app.secretKey | quote }}
  {{- if .Values.sso.clientId }}
  SSO_CLIENT_ID: {{ .Values.sso.clientId | quote }}
  SSO_CLIENT_SECRET: {{ .Values.sso.clientSecret | quote }}
  SSO_AUTH_URL: {{ .Values.sso.authUrl | quote }}
  SSO_TOKEN_URL: {{ .Values.sso.tokenUrl | quote }}
  {{- end }}
