# ==============================================================================
# Hardened Maker Management Platform Builds
# ==============================================================================
FROM ghcr.io/maker-management-platform/agent:main AS agent
USER root
RUN if [ -f /etc/alpine-release ]; then \
      apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*; \
    else \
      apt-get update && apt-get upgrade -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
    fi

FROM ghcr.io/maker-management-platform/mmp-ui:master AS ui
USER root
RUN if [ -f /etc/alpine-release ]; then \
      apk update && apk upgrade --no-cache && rm -rf /var/cache/apk/*; \
    else \
      apt-get update && apt-get upgrade -y && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*; \
    fi
