apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "keryx.fullname" . }}-orchestrator-sa
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "keryx.fullname" . }}-orchestrator-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch", "watch"]
  - apiGroups: ["http.keda.sh"]
    resources: ["httpscaledobjects"]
    verbs: ["get", "list", "patch", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "keryx.fullname" . }}-orchestrator-rb
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keryx.fullname" . }}-orchestrator-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "keryx.fullname" . }}-orchestrator-role
  apiGroup: rbac.authorization.k8s.io
