{{- range $serviceName, $service := .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keryx.fullname" $ }}-{{ $serviceName }}
  labels:
    {{- include "keryx.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: {{ $serviceName }}
{{- end }}
