image:
  # -- image repository
  repository: onerahmet/openai-whisper-asr-webservice
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent

env: 
    ASR_MODEL: base
    ASR_ENGINE: openai_whisper
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 9000

ingress:
  main:
    enabled: true
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-dns
    ingressClassName: "traefik"
    hosts: 
       - host: openai-whisper-asr-webservice.p.zacharie.org
         paths:
           - path: /
             pathType: Prefix
    tls:
      - secretName: openai-whisper-asr-webservice.p.zacharie.org-tls
        hosts:
          - openai-whisper-asr-webservice.p.zacharie.org
