apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: {{ .Values.redis.service.port }}
        resources:
          {{- toYaml .Values.redis.resources | nindent 10 }}
