apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kryptos.fullname" . }}
  labels:
    {{- include "kryptos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kryptos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kryptos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kryptos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: backend
              containerPort: 5000
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.sealedSecret }}
          envFrom:
            - secretRef:
                name: {{ .Values.sealedSecret.name | default (include "kryptos.fullname" .) }}
          {{- end }}
          env:
            - name: GIT_REPO
              value: {{ .Values.config.git.repo | quote }}
            - name: GIT_BRANCH
              value: {{ .Values.config.git.branch | quote }}
            - name: VAULT_ADDR
              value: {{ .Values.config.vault.address | quote }}
          volumeMounts:
            {{- if or .Values.config.sealedSecrets.certificate .Values.config.sealedSecrets.existingConfigMap }}
            - name: certs
              mountPath: /app/certs
              readOnly: true
            {{- end }}
            {{- if .Values.persistence.enabled }}
            - name: db
              mountPath: {{ .Values.persistence.mountPath | default "/database" }}
            {{- end }}
      volumes:
        {{- if or .Values.config.sealedSecrets.certificate .Values.config.sealedSecrets.existingConfigMap }}
        - name: certs
          configMap:
            name: {{ .Values.config.sealedSecrets.existingConfigMap | default (printf "%s-certs" (include "kryptos.fullname" .)) }}
            items:
              - key: {{ .Values.config.sealedSecrets.existingConfigMapKey | default "sealed-secrets.crt" }}
                path: sealed-secrets.crt
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: db
          persistentVolumeClaim:
            claimName: {{ include "kryptos.fullname" . }}-db
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
