{{- if .Values.sealedSecret -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sealedSecret.name | default (include "kryptos.fullname" .) }}
  labels:
    {{- include "kryptos.labels" . | nindent 4 }}
  {{- with .Values.sealedSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecret.data | nindent 4 }}
  template:
    metadata:
      labels:
        {{- include "kryptos.selectorLabels" . | nindent 8 }}
      {{- with .Values.sealedSecret.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    type: Opaque
{{- end }}
