image:
  # -- image repository
  repository: registry.gitlab.com/connectical/container/polaris
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: IfNotPresent

# env: 
#   MODEL_IDLE_TIMEOUT: 300
#   ASR_DEVICE: cpu
#   ASR_QUANTIZATION: int8
#   ASR_MODEL_PATH: /data/whisper
#   SUBTITLE_MAX_LINE_WIDTH: '1000'
#   SUBTITLE_MAX_LINE_COUNT: '2'
#   SUBTITLE_HIGHLIGHT_WORDS: 'false'
#   HF_TOKEN: 'your_token_here'
#   ASR_ENGINE: polaris
#   ASR_MODEL: distil-large-v3
  
# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5050

ingress:
  main:
    enabled: true
    labels: {}
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-dns
    ingressClassName: "traefik"
    hosts: 
       - host: polaris.p.zacharie.org
         paths:
           - path: /
             pathType: Prefix
    tls:
      - secretName: polaris.p.zacharie.org-tls
        hosts:
          - polaris.p.zacharie.org

persistence:
  data:
    enabled: true
    mountPath: /var/lib/polaris
  music:
    enabled: true
    mountPath: /music
  cache:
    enabled: true
    mountPath: /var/cache/polaris