{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: appflowy
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingress.className }}"
    cert-manager.io/cluster-issuer: "{{ .Values.ingress.tls.clusterIssuer }}"
spec:
  rules:
  - host: {{ .Values.global.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: appflowy-cloud
            port:
              number: 8000
  tls:
  - hosts:
    - {{ .Values.global.domain }}
    secretName: appflowy-tls
{{- end }}